name: Release
on:
  push:

jobs:
  generate-iso:
    runs-on: ubuntu-latest
    container:
      image: debian
    env:
      PKG: "frr frr-doc nmap netcat-traditional telnet wget curl apache2 ca-certificates net-tools nftables iptables ebtables bind9 nginx dnsmasq ifupdown bind9-dnsutils isc-dhcp-client neovim"
    steps:
      - run: apt update && apt install -y apt-rdepends dpkg-dev genisoimage
      - run: apt download $(apt-rdepends $PKG|grep -v "^ "|grep --invert-match -e debconf-2.0 -e libblas.so.3 -e cron-daemon -e libaprutil1-dbd-freetds -e "^host$")
      - run: dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
      - run: genisoimage -lJR -o debian-netpkgs.iso .

      - uses: actions/upload-artifact@v4
        with:
          name: debian-netpkgs.iso
          path: debian-netpkgs.iso
          if-no-files-found: error
          compression-level: 0
    
  modify-img-networkd:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - uses: actions/checkout@v4
      - run: apt update && apt install -y libguestfs-tools
      - run: wget --quiet https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      # installing some basic tools
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y procps'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y nano neovim'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --hostname debian
      
      # offline apt
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'mv /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak && echo "deb [trusted=yes] file:/mnt/cdrom ./" > /etc/apt/sources.list.d/cdrom.list && rm -rf /var/lib/apt/lists/*'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --copy-in cdrom.mount:/etc/systemd/system/
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'mkdir -p /mnt/cdrom && systemctl enable cdrom.mount'

      - run: mv debian-12-nocloud-amd64.qcow2 debian12-netlab-networkd.qcow2
      - uses: actions/upload-artifact@v4
        with:
          name: debian12-netlab-networkd.qcow2
          path: debian12-netlab-networkd.qcow2
          if-no-files-found: error
          compression-level: 0
  
  modify-img-ifupdown:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - uses: actions/checkout@v4
      - run: apt update && apt install -y libguestfs-tools
      - run: wget --quiet https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      # installing some basic tools
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y procps'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y nano neovim'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --hostname debian
      
      # installing ifupdown as network configuration tool
      - name: install and enable networking.service in image
        run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y ifupdown && systemctl disable systemd-networkd.service systemd-networkd.socket && systemctl mask systemd-networkd.service systemd-networkd.socket && systemctl enable networking.service'
    
      # offline apt
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'mv /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak && echo "deb [trusted=yes] file:/mnt/cdrom ./" > /etc/apt/sources.list.d/cdrom.list && rm -rf /var/lib/apt/lists/*'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --copy-in cdrom.mount:/etc/systemd/system/
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'mkdir -p /mnt/cdrom && systemctl enable cdrom.mount'
      

      - run: mv debian-12-nocloud-amd64.qcow2 debian12-netlab-ifupdown.qcow2
      - uses: actions/upload-artifact@v4
        with:
          name: debian12-netlab-ifupdown.qcow2
          path: debian12-netlab-ifupdown.qcow2
          if-no-files-found: error
          compression-level: 0

  generate-gns3a:
    needs: [generate-iso, modify-img-networkd, modify-img-ifupdown]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # systemd-networkd image
      - name: Download debian12-netlab-networkd.qcow2
        uses: actions/download-artifact@v4
        with:
          name: debian12-netlab-networkd.qcow2
      - name: replace md5sum of debian-12-nocloud-amd64.qcow2
        run: sed -i "s/placeholderfornetworkdmd5/$(md5sum debian12-netlab-networkd.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a
      - run: sed -i "s/placeholderfornetworkdsize/$(wc -c debian12-netlab-networkd.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a

      # ifupdown image
      - name: Download debian12-netlab-ifupdown.qcow2
        uses: actions/download-artifact@v4
        with:
          name: debian12-netlab-ifupdown.qcow2
      - name: replace md5sum of debian-12-nocloud-amd64.qcow2
        run: sed -i "s/placeholderforupdownmd5/$(md5sum debian12-netlab-ifupdown.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a
      - run: sed -i "s/placeholderforupdownsize/$(wc -c debian12-netlab-ifupdown.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a

      # apt iso
      - name: Download debian-netpkgs.iso
        uses: actions/download-artifact@v4
        with:
          name: debian-netpkgs.iso
      - name: replace md5sum of debian-netpkgs.iso
        run: sed -i "s/placeholderforisomd5/$(md5sum debian-netpkgs.iso | cut -d' ' -f1)/g" debian-jle.gns3a
      - run: sed -i "s/placeholderforisosize/$(wc -c debian-netpkgs.iso | cut -d' ' -f1)/g" debian-jle.gns3a

      - uses: actions/upload-artifact@v4
        with:
          name: debian-jle.gns3a
          path: debian-jle.gns3a
          if-no-files-found: error
          compression-level: 0
