name: Release
on:
  push:

jobs:
  generate-iso:
    runs-on: ubuntu-latest
    container:
      image: debian
    env:
      PKG: "frr frr-doc nmap netcat-traditional telnet wget curl apache2 ca-certificates net-tools nftables iptables ebtables bind9 nginx dnsmasq ifupdown bind9-dnsutils isc-dhcp-client neovim"
    steps:
      - run: apt update && apt install -y apt-rdepends dpkg-dev genisoimage
      - run: apt download $(apt-rdepends $PKG|grep -v "^ "|grep --invert-match -e debconf-2.0 -e libblas.so.3 -e cron-daemon -e libaprutil1-dbd-freetds -e "^host$")
      - run: dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
      - run: genisoimage -lJR -o debian-netpkgs.iso .

      - uses: actions/upload-artifact@v4
        with:
          name: debian-netpkgs.iso
          path: debian-netpkgs.iso
          if-no-files-found: error
          compression-level: 0
