name: Release
on:
  push:

jobs:
  generate-iso:
    runs-on: ubuntu-latest
    container:
      image: debian
    env:
      PKG: "frr frr-doc nmap netcat-traditional telnet wget curl apache2 ca-certificates net-tools nftables iptables ebtables bind9 nginx dnsmasq ifupdown bind9-dnsutils isc-dhcp-client neovim"
    steps:
      - run: apt update && apt install -y apt-rdepends dpkg-dev genisoimage
      - run: apt download $(apt-rdepends $PKG|grep -v "^ "|grep --invert-match -e debconf-2.0 -e libblas.so.3 -e cron-daemon -e libaprutil1-dbd-freetds -e "^host$")
      - run: dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
      - run: genisoimage -lJR -o debian-netpkgs.iso .

      - uses: actions/upload-artifact@v4
        with:
          name: debian-netpkgs.iso
          path: debian-netpkgs.iso
          if-no-files-found: error
          compression-level: 0
    
  modify-img:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - run: apt update && apt install -y libguestfs-tools
      - run: wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2

      - name: install and enable networking.service in image
        run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y ifupdown && systemctl disable systemd-networkd.service systemd-networkd.socket && systemctl mask systemd-networkd.service systemd-networkd.socket && systemctl enable networking.service'
      - run: virt-customize -a debian-12-nocloud-amd64.qcow2 --run-command 'apt update && apt install -y nano neovim'

      - uses: actions/upload-artifact@v4
        with:
          name: debian-12-nocloud-amd64.qcow2
          path: debian-12-nocloud-amd64.qcow2
          if-no-files-found: error
          compression-level: 0


  generate-gns3a:
    needs: [generate-iso, modify-img]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download debian-netpkgs.iso
        uses: actions/download-artifact@v4
        with:
          name: debian-netpkgs.iso
      - name: Download debian-netpkgs.iso
        uses: actions/download-artifact@v4
        with:
          name: debian-12-nocloud-amd64.qcow2
      
      - name: replace md5sum of debian-12-nocloud-amd64.qcow2
        run: sed -i "s/7dd9da43795fea484e723f057c237971/$(md5sum debian-12-nocloud-amd64.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a
      - run: sed -i "s/414372864/$(wc -c debian-12-nocloud-amd64.qcow2 | cut -d' ' -f1)/g" debian-jle.gns3a
      - name: replace md5sum of debian-netpkgs.iso
        run: sed -i "s/3192d003067cea87640e989d3933edff/$(md5sum debian-netpkgs.iso | cut -d' ' -f1)/g" debian-jle.gns3a
      - run: sed -i "s/58423296/$(wc -c debian-netpkgs.iso | cut -d' ' -f1)/g" debian-jle.gns3a

      - uses: actions/upload-artifact@v4
        with:
          name: debian-jle.gns3a
          path: debian-jle.gns3a
          if-no-files-found: error
          compression-level: 0
